-- MySQL Workbench Synchronization
-- Generated: 2015-09-15 21:43
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Jonathan Morales Salazar

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `blogcapa8`.`noticia` 
ADD COLUMN `seo_slug` VARCHAR(100) NOT NULL COMMENT '' AFTER `titulo`;

ALTER TABLE `blogcapa8`.`categoria` 
ADD COLUMN `seo_slug` VARCHAR(100) NULL DEFAULT NULL COMMENT '' AFTER `categoria`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
